- name: Fix URL
  set_fact:
    jdk_tarball_url: "{{ jdk_tarball_url }}.tar.gz"
  when: jdk_tarball_url.find('tar.gz') == -1

- name: print debug
  debug:
    msg: "url {{ jdk_tarball_url }} will download to {{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"

- name: get JDK tarball (as tar.gz file)
  get_url:
    url:     "{{ jdk_tarball_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"

- name: mkdir for Java
  file:
    path: "{{ java_install_dir }}/jdk{{ jdk_version }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: install JDK via tarball file
  unarchive:
    src: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
    dest: "{{ java_install_dir }}"
    owner: root
    group: root
    mode: "go-w"
    copy: no


- block:

    # No link creation is necessary on Mac OS X -- 
    # the package installer automatically creates symlinks in /usr/bin.

    - name: link "{{ java_install_dir }}/{{ java_default_link_name }}"
      file:
        dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
        src: "{{ java_install_dir }}/jdk{{ jdk_version }}"
        state: link

    - name: alternatives link for "java"
      alternatives:
        name: java
        link: /usr/bin/java
        path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/java"

    - name: alternatives link for "javac"
      alternatives:
        name: javac
        link: /usr/bin/javac
        path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/javac"

    - name: alternatives link for "jar"
      alternatives:
        name: jar
        link: /usr/bin/jar
        path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/jar"

    - name: check if "java_sdk" target exists
      stat: path=/usr/lib/jvm/java
      register: filecheck

    - name: alternatives link for "java_sdk"
      alternatives:
        name: java_sdk
        link: /usr/lib/jvm/java
        path: "{{ java_install_dir }}/{{ java_default_link_name }}"
      when: filecheck and filecheck.stat.exists
