---
- hosts: inst
  vars:
        java_version: 8
        java_subversion: 111
        java_download_path: "/tmp"
        java_download_from_oracle: true
        java_remove_download: false
        java_install_jce: false
        java_set_javahome: true
        java_override_url: true

  name: configuration play
  user: ubuntu

  # https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f#gistcomment-1914049
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      become: true
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: false
    - setup: # aka gather_facts



  tasks:

    - name: Install unzip
      become: true
      apt:
        name: unzip
        update_cache: true

    - name: Set Variables
      include: set-role-variables.yml

      # override java download url use for old java versions
    - name: override java download url
      set_fact:
        jdk_tarball_url: "https://s3.amazonaws.com/dev-overops/java/jdk-8u111-linux-x64.tar.gz"
      when: java_override_url is defined

    - name: Install java
      include: install_java.yml

    - name: get Takipi tomcat
      become: true
      get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.zip dest=/mnt/Tomcat.zip


    - name: extract Takipi tomcat
      become: true
      unarchive:
        src: /mnt/Tomcat.zip
        dest: /mnt/
        remote_src: yes

    - name: clean tomcat
      become: true
      shell: rm -rf *
      args:
        chdir: /mnt/apache-tomcat-8.5.5/webapps/
    - name: create folder
      become: true
      file:
        path: /mnt/apache-tomcat-8.5.5/webapps/ROOT
        state: directory
        mode: 0755

    - name: get takipi backend
      become: true
      get_url: url=https://s3-eu-west-1.amazonaws.com/alon-dotan/backend.war dest=/mnt/apache-tomcat-8.5.5/webapps/backend.war

    - name: extract Takipi Backend
      become: true
      unarchive:
        src: /mnt/apache-tomcat-8.5.5/webapps/backend.war
        dest: /mnt/apache-tomcat-8.5.5/webapps/ROOT/
        remote_src: yes

    - name: start tomcat
      become: true
      shell: nohup bash ./catalina.sh start
      args:
        chdir: /mnt/apache-tomcat-8.5.5/bin
      tags: run
